forge 'forge.puppetlabs.com'

mod 'puppetlabs/ntp', '3.1.2'
mod 'puppetlabs/stdlib', '4.3.2'
mod 'puppetlabs/firewall', '1.1.3'
mod 'saz/sudo', '3.0.6'
mod 'spiette/selinux', '0.5.4'
mod 'puppetlabs/lvm', '0.3.2'
mod 'abstractit/puppet', '2.1.2'
mod 'puppetlabs/inifile', '1.4.1'
mod 'zleslie/pkgng', 0.2.5'
